// Generated by gencpp from file nlu/midiCC.msg
// DO NOT EDIT!


#ifndef NLU_MESSAGE_MIDICC_H
#define NLU_MESSAGE_MIDICC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nlu
{
template <class ContainerAllocator>
struct midiCC_
{
  typedef midiCC_<ContainerAllocator> Type;

  midiCC_()
    : channel()
    , control()
    , value()  {
    }
  midiCC_(const ContainerAllocator& _alloc)
    : channel(_alloc)
    , control(_alloc)
    , value(_alloc)  {
    }



   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _channel_type;
  _channel_type channel;

   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _control_type;
  _control_type control;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _value_type;
  _value_type value;




  typedef boost::shared_ptr< ::nlu::midiCC_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nlu::midiCC_<ContainerAllocator> const> ConstPtr;

}; // struct midiCC_

typedef ::nlu::midiCC_<std::allocator<void> > midiCC;

typedef boost::shared_ptr< ::nlu::midiCC > midiCCPtr;
typedef boost::shared_ptr< ::nlu::midiCC const> midiCCConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nlu::midiCC_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nlu::midiCC_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nlu

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
<<<<<<< HEAD
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'nlu': ['/home/m/catkin_ws/src/nlu/msg']}
=======
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'nlu': ['/home/m/catkin_ws/src/nlu/msg']}
>>>>>>> b883065350307bba6f0f0bd12bed736de3baf565

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nlu::midiCC_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlu::midiCC_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nlu::midiCC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nlu::midiCC_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlu::midiCC_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlu::midiCC_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nlu::midiCC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0aa03c0d63d3de89de98b89232fcb63f";
  }

  static const char* value(const ::nlu::midiCC_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0aa03c0d63d3de89ULL;
  static const uint64_t static_value2 = 0xde98b89232fcb63fULL;
};

template<class ContainerAllocator>
struct DataType< ::nlu::midiCC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nlu/midiCC";
  }

  static const char* value(const ::nlu::midiCC_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nlu::midiCC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16[]  channel\n\
uint16[]  control\n\
int16[]   value\n\
";
  }

  static const char* value(const ::nlu::midiCC_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nlu::midiCC_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.channel);
      stream.next(m.control);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct midiCC_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nlu::midiCC_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nlu::midiCC_<ContainerAllocator>& v)
  {
    s << indent << "channel[]" << std::endl;
    for (size_t i = 0; i < v.channel.size(); ++i)
    {
      s << indent << "  channel[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.channel[i]);
    }
    s << indent << "control[]" << std::endl;
    for (size_t i = 0; i < v.control.size(); ++i)
    {
      s << indent << "  control[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.control[i]);
    }
    s << indent << "value[]" << std::endl;
    for (size_t i = 0; i < v.value.size(); ++i)
    {
      s << indent << "  value[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NLU_MESSAGE_MIDICC_H
